-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 09:53:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema m426projekt
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `m426projekt`;
CREATE DATABASE IF NOT EXISTS `m426projekt` DEFAULT CHARACTER SET utf8mb4;
USE `m426projekt`;

-- -----------------------------------------------------
-- Table `m426projekt`.`filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m426projekt`.`filme`;
CREATE TABLE IF NOT EXISTS `m426projekt`.`filme` (
  `fid` INT NOT NULL AUTO_INCREMENT,
  `titel` VARCHAR(45) NOT NULL,
  `beschreibung` TEXT NOT NULL,
  `darsteller` TEXT NOT NULL,
  `regisseur` VARCHAR(45) NOT NULL,
  `dauer` INT NOT NULL,
  `startdatum` DATE NOT NULL,
  `genre` VARCHAR(155) NOT NULL,
  `altersgrenze` INT NOT NULL,
  `trailer` TEXT NOT NULL,
  `cover` TEXT NOT NULL,
  PRIMARY KEY (`fid`))
ENGINE = InnoDB;

INSERT INTO `filme` (`titel`, `beschreibung`, `darsteller`, `regisseur`, `dauer`, `startdatum`, `genre`, `altersgrenze`, `trailer`, `cover`) VALUES
('Ghostbusters: Frozen Empire', 'Die Familie Spengler kehrt an den Ort zurück, an dem alles begann — die Feuerwache in New York. Als ein Artefakt eine böse Macht freisetzt, müssen die alten und die neuen Ghostbusters zusammenspannen, um die Welt vor einer zweiten Eiszeit zu bewahren.', 'Finn Wolfhard, Mckenna Grace, Bill Murray, Patton Oswalt, Carrie Coon, Paul Rudd', 'Gil Kenan', 115, '2024-08-01', 'Jugend, Kids & Family, Sci-Fi, Komödie, Abenteuer, Fantasy', 12, 'https://youtu.be/HpOBXh02rVc?si=EGY33wB-wB4efDcP', 'https://medstore.bluecinema.ch/1017_168_5d2d01811cf1dabc1fb914bf6b00a28d14530a12.jpg'),
('Godzilla x Kong: The New Empire', 'Der epische Kampf geht weiter! Der allmächtige Kong und der furchteinflössende Godzilla treten gemeinsam gegen eine gewaltige, unbekannte Bedrohung an, die in unserer Welt verborgen liegt — und die ihre gesamte Existenz infrage stellt.', 'Rebecca Hall, Rachel House, Alex Ferns, Kaylee Hottle, Dan Stevens, Brian Tyree Henry', 'Adam Wingard', 115, '2024-08-01', 'Sci-Fi, Action, Thriller, Abenteuer', 12, 'https://youtu.be/eHS212bmQIw?si=RbN9KEeyXo2n2AMc', 'https://medstore.bluecinema.ch/1016_330_5791947f80f543bfca0b7327581be004ad219119.jpg'),
('Kung Fu Panda 4', 'Drachenkrieger PO tritt gegen eine neue Art von Super-Schurkin an: Das Chamäleon ist in der Lage, sich in jede beliebige Kreatur zu verwandeln. Zusammen mit der cleveren Steppenfüchsin Zhen versucht PO das Tal des Friedens vor dem Chamäleon zu beschützen.', 'Ronny Chieng, Lori Tan Chinn, Ke Huy Quan, Viola Davis, James Hong, Jack Black, lan McShane, Cece Valentina, Bryan Cranston, Dustin Hoffman, Awkwafina', 'Mike Mitchell, Stephanie Stine', 94, '2024-08-01', 'Fantasy, Familienfilm, Abenteuer, Komödie, Action, Animation, Jugend, Kids & Family', 6, 'https://youtu.be/t-mmivasE5E?si=qIUtcpT2nQwnXLXs', 'https://medstore.bluecinema.ch/1017_424_764977016a7c5fbe478b3bde92ca38fdfbb7636f_d.jpg'),
('Sowas von super!', 'Das Leben der elfjährigen Hedvig wird völlig auf den Kopf gestellt, als sie unerwartet aufgefordert wird, ihren Vater als Superheldin der Stadt zu ersetzen. Mit ihrer Grossmutter bildet Hedvig ein so ungewöhnliches wie bemerkenswertes Superhelden-Team!', 'Atle Antonsen, Johannes Kjærnes, Desta Marie Beeder, Charlotte Frogner, Hennika Huuse, Henriette Marø', 'Rasmus A. Sivertsen', 77, '2024-08-01', 'Animation', 3, 'https://youtu.be/O1b-QcEF1ZE?si=H4UbiyF87Qsq-lnU', 'https://medstore.bluecinema.ch/1019_381_1939db357b199c837a8dd2c4625fda8c0d8570cc.jpg'),
('Dune: Part Two', 'Paul Atreides begibt sich mit Chani und den Fremen auf einen Rachefeldzug gegen die Verschwörer, die seine Familie vernichtet haben. Dabei steht er auch vor der Wahl zwischen der Liebe seines Lebens und dem Schicksal des Universums. Epische Fortsetzung.', 'Javier Bardem, Zendaya, Josh Brolin, Florence Pugh, Timothée Chalamet, Léa Seydoux, Austin Butler, Stellan Skarsgård, Dave Bautista, Christopher Walken, Rebecca Ferguson, Charlotte Rampling', 'Denis Villeneuve', 166, '2024-08-01', 'Sci-Fi, Action, Abenteuer, Drama', 12, 'https://youtu.be/Way9Dexny3w?si=Zl0Id4_TJhCdZKXs', 'https://medstore.bluecinema.ch/1016_059_55ca8b927ebdfd0622a74bfdba9adf07d66ad5fd.jpg');

-- -----------------------------------------------------
-- Table `m426projekt`.`geschenkkarten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m426projekt`.`geschenkkarten`;
CREATE TABLE IF NOT EXISTS `m426projekt`.`geschenkkarten` (
  `gid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `preis` DECIMAL(10,2) NULL,
  `beschreibung` TEXT NULL,
  `verfuegbar` TINYINT(1) NULL,
  PRIMARY KEY (`gid`))
ENGINE = InnoDB;

INSERT INTO `geschenkkarten` (`name`, `preis`, `beschreibung`, `verfuegbar`) VALUES
('Standard Karte', 25.00, 'Gültig für alle Filme und Snacks.', 1),
('Premium Karte', 50.00, 'Gültig für alle Premium-Plätze und spezielle Veranstaltungen.', 1),
('Kinder Karte', 10.00, 'Gültig für alle Kinderfilme.', 1),
('Gold Karte', 100.00, 'Gültig für ein Jahr unbegrenzten Zugang.', 1),
('Silber Karte', 75.00, 'Gültig für sechs Monate unbegrenzten Zugang.', 1);

-- -----------------------------------------------------
-- Table `m426projekt`.`kinosaele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m426projekt`.`kinosaele`;
CREATE TABLE IF NOT EXISTS `m426projekt`.`kinosaele` (
  `kid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `standort` VARCHAR(45) NULL,
  `kapazität` INT NULL,
  `nutzungen` VARCHAR(45) NULL,
  `beschreibung` TEXT NULL,
  `bilder` TEXT NULL,
  PRIMARY KEY (`kid`))
ENGINE = InnoDB;

INSERT INTO `kinosaele` (`name`, `standort`, `kapazität`, `nutzungen`, `beschreibung`, `bilder`) VALUES
('Saal 1', 'Zentrum', 150, 'Filmvorführungen', 'Hauptsaal für Blockbuster.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/04/RedCarpet_saal1_technik-768x512.jpg'),
('Saal 2', 'Nordflügel', 100, 'Filmvorführungen', 'Ideal für erotik Vorstellungen.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/02/Saal-1-450x450.jpg'),
('Saal 3', 'Südflügel', 200, 'Veranstaltungen', 'Grossraum für Events und Sonderveranstaltungen.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/03/KinoKoni_Saal-1-3-500x333.jpeg'),
('Saal 4', 'Ostflügel', 50, 'Private Vorführungen', 'Kleiner Saal für private Anlässe.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/03/KinoKoni_Saal-4-1-500x333.jpeg'),
('Saal 5', 'Westflügel', 120, 'Filmvorführungen', 'Modern ausgestatteter Kinosaal.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/03/KK_0002.jpg');

-- -----------------------------------------------------
-- Table `m426projekt`.`partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m426projekt`.`partner`;
CREATE TABLE IF NOT EXISTS `m426projekt`.`partner` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;

INSERT INTO `partner` (`name`, `url`) VALUES
('Filmverleih Gmbh', 'http://filmverleih.com'),
('Snacks & Co', 'http://snacksundco.com'),
('EventOrganizer Pro', 'http://eventorganizerpro.com'),
('TechAudio Solutions', 'http://techaudio.com'),
('PromoAdvert Marketing', 'http://promoadvert.com');

-- -----------------------------------------------------
-- Table `m426projekt`.`raeume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m426projekt`.`raeume`;
CREATE TABLE IF NOT EXISTS `m426projekt`.`raeume` (
  `name` VARCHAR(255) NOT NULL,
  `beschreibung` TEXT NULL,
  `bild` TEXT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;

INSERT INTO `raeume` (`name`, `beschreibung`, `bild`) VALUES
('Empfangshalle', 'Eingangsbereich des Kinos mit Ticketverkauf und Informationen.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/03/KinoKoni_Foyer-EG-3-2-1024x683-1-500x333.jpeg'),
('VIP-Lounge', 'Exklusiver Bereich für Premium-Gäste.', 'https://redcarpet-eventlocations.ch/wp-content/uploads/2022/03/KinoKoni_Foyer-EG-2-1-1024x683-1-500x333.jpeg'),
('Projektionsraum', 'Technikraum für die Filmprojektoren.', 'https://kinoleitfaden.de/assets/components/phpthumbof/cache/DSC2002.18bc92fff3e5d117f2e36c4d60b97c3b.jpg'),
('Snack Bar', 'Verkauf von Snacks und Getränken.', 'https://partner-tech.eu/wp-content/uploads/2017/03/Cinema-01-1.jpg'),
('Garderobe', 'Bereich für die Aufbewahrung von Jacken und persönlichen Gegenständen.', 'https://www.imago-images.de/bild/st/0116296199/s.jpg');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;